
openapi: 3.0.0
info:
  title: API de Sistema de Facturación y Stock
  description: API para gestionar facturas, productos, clientes, proveedores, inventario y reportes.
  version: 1.0.0
servers:
  - url: localhost:8080/par2024

paths:
  /facturas:
    get:
      summary: Obtener todas las facturas
      responses:
        '200':
          description: Lista de facturas obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Factura'
    post:
      summary: Crear una nueva factura
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Factura'
      responses:
        '201':
          description: Factura creada correctamente
        '400':
          description: Datos de la factura inválidos
  /facturas/{id}:
    get:
      summary: Obtener una factura por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único de la factura
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Factura obtenida correctamente
        '404':
          description: Factura no encontrada
    put:
      summary: Actualizar una factura existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único de la factura
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Factura'
      responses:
        '200':
            description: Factura actualizada correctamente
        '400':
            description: Datos de la factura inválidos
        '404':
            description: Factura no encontrada

    delete:
      summary: Eliminar una factura existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único de la factura
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Factura eliminada correctamente
        '404':
          description: Factura no encontrada
  /productos:
    get:
      summary: Obtener todos los productos en stock
      responses:
        '200':
          description: Lista de productos obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Producto'
    post:
      summary: Crear un nuevo producto en el stock
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '201':
          description: Producto creado correctamente
        '400':
          description: Datos del producto inválidos
  /productos/{id}:
    get:
      summary: Obtener un producto por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del producto
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Producto obtenido correctamente
        '404':
          description: Producto no encontrado

    put:
      summary: Actualizar un producto existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del producto
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '200':
          description: Producto actualizado correctamente
        '400':
          description: Datos del producto inválidos
        '404':
          description: Producto no encontrado

    delete:
      summary: Eliminar un producto existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del producto
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Producto eliminado correctamente
        '404':
          description: Producto no encontrado
  /clientes:
    get:
      summary: Obtener todos los clientes registrados
      responses:
        '200':
          description: Lista de clientes obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'
    post:
      summary: Crear un nuevo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '201':
          description: Cliente creado correctamente
        '400':
          description: Datos del cliente inválidos


  /clientes/{id}:
    get:
      summary: Obtener un cliente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del cliente
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Cliente obtenido correctamente
        '404':
          description: Cliente no encontrado

    put:
      summary: Actualizar los datos de un cliente existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del cliente
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '200':
          description: Cliente actualizado correctamente
        '400':
          description: Datos del cliente inválidos
        '404':
          description: Cliente no encontrado

    delete:
      summary: Eliminar un cliente existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del cliente
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Cliente eliminado correctamente
        '404':
          description: Cliente no encontrado

  /proveedores:
    get:
      summary: Obtener todos los proveedores registrados
      responses:
        '200':
          description: Lista de proveedores obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Proveedor'
    post:
      summary: Crear un nuevo proveedor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Proveedor'
      responses:
        '201':
          description: Proveedor creado correctamente
        '400':
          description: Datos del proveedor inválidos

  /proveedores/{id}:
    get:
      summary: Obtener un proveedor por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del proveedor
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Proveedor obtenido correctamente
        '404':
          description: Proveedor no encontrado



    put:
      summary: Actualizar los datos de un proveedor existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del proveedor
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Proveedor'
      responses:
        '200':
          description: Proveedor actualizado correctamente
        '400':
          description: Datos del proveedor inválidos
        '404':
          description: Proveedor no encontrado

    delete:
      summary: Eliminar un proveedor existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del proveedor
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Proveedor eliminado correctamente
        '404':
          description: Proveedor no encontrado


components:
  schemas:
    Factura:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID único de la factura
        numero:
          type: string
          description: Número de la factura
        cliente:
          type: string
          description: Nombre del cliente
        total:
          type: number
          format: double
          description: Total de la factura
      required:
        - numero
        - cliente
        - total
        
    Producto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID único del producto
        nombre:
          type: string
          description: Nombre del producto
        precio:
          type: number
          format: double
          description: Precio del producto
        descripcion:
          type: string
          description: Descripción del producto
      required:
        - nombre
        - precio
    Cliente:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID único del producto
        nombre:
          type: string
          description: Nombre del cliente
        ruc:
          type: string
          description: Numero de ruc del cliente
        celular:
          type: number
          description: Nro de celular
      required:
        - nombre
        - ruc
    Proveedor:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID único del producto
        nombre:
          type: string
          description: Nombre del cliente
        ruc:
          type: string
          description: Numero de ruc del cliente
        celular:
          type: number
          description: Nro de celular
      required:
        - nombre
        - ruc

